### ISSUE TITLE
Add choo-expose

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#211]
Looks handy
https://github.com/yoshuawuyts/choo-expose

**Comment by ungoldman** [comment]
It's weird though, it's definitely not exposing the actual choo instance.

https://github.com/yoshuawuyts/choo-expose/blob/master/index.js#L10

**Comment by zeke** [comment]
What is going on here, @yoshuawuyts? :)

**Comment by yoshuawuyts** [comment]
oh yeah, it just exposes `choo.emit`, `choo.state` and the custom `choo.log` property which contains a log of the last 150 emitted events. I figured these shorthands might be a bit easier to work with rather than needing to do something like: `choo.emitter.emit` or smth. Haha, that was my reasoning so far tho, but please do let me know if it makes sense at all. This is one of those modules I just wrote cause I thought it was handy, but no clue if it works for others haha :sparkles:

**Comment by ungoldman** [comment]
I think I get it, so more like a little tool belt for common dev/debug tasks that would be a bit more work to get to via something like `window.app = choo()`?

**Comment by yoshuawuyts** [comment]
Yep, that's what it is :D

**Comment by ungoldman** [comment]
Cool, thanks @yoshuawuyts!
