### ISSUE TITLE
reconsider how we shuffle

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/hyperamp#232]
I showed the latest version of the app to @obensource today he made the fair point that the shuffle style is a little unusual -- rather than making the `next` button choose a random song to play next, we do a random sort on the entire library and show the new order.

This has a couple drawbacks:

- indexes are messed up by shuffling
  - currently playing song display is wrong when toggling shuffling, in both list and player
- next shuffle doesn't make playlist jump around (some might like this but I kind of like when it *does* jump around while keeping my sort preferences intact)
- sorting is all messed up by this (if we ever implement sorting by column)

so I think maybe we should simplify how we shuffle, and just make the `next` behavior be to pick a random song when it's on (though would be nice to preserve shuffle history on `prev` in that context)

🔀  thoughts @bcomnes? 🔀

**Comment by bcomnes** [comment]
Its difficult to shuffle as you go, because random numbers overlap, so to shuffle, you need to create a shuffled set of all tracks.  Right now we just show that, but you are right iTunes and others keep whatever sort order you have visually and jump around referencing the shuffle set as it goes.  Thats how you can go forward and backwards predictably. 

Most of these issues stem from the fact we haven't implemented the correct set of data structures needed to fully capture what you would expect out of a media player.

**Comment by bcomnes** [comment]
We do what OP suggested now!
