### ISSUE TITLE
Support star ratings in POPM ID3 tag

### ISSUE THREAD

**Issue by tmcw** [hypermodules/hyperamp#339]
Expressing [ratings in ID3 tags](https://en.wikipedia.org/wiki/ID3#ID3v2_rating_tag_issue) is apparently a bit of a tricky standards area, but there is a 80%-of-players-use-it (excepting iTunes) which hyperamp could use as well.

Noting that hyperamp doesn't do any ID3 editing yet (as far as I can tell) and this might be something you want to keep out of scope, but it's (maybe personally? unusually?) a feature that I heavily use in other players.

**Comment by bcomnes** [comment]
Looks like https://github.com/borewit/music-metadata#ratingtostars-function supports it, so we can certainly show it.  But yeah, we don't have any kind of editing functionality unfortunately, mainly because implementations of that is locked away in difficult to wrap https://taglib.org calls.  

There was an attempt over at https://github.com/voltraco/node-taglib2 a while ago, but I just haven't had the time to pick up where that is left off.

**Comment by bcomnes** [comment]
Project is mostly timed out. Closing for now 😢
