### ISSUE TITLE
Reduce scope

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#5]
After thinking about all the things we are trying to accomplish in this project, and realizing I haven't even ever tried to build a music library/player before, we should probably work on some simpler goals before we reach too high.

Here is what I propose:

- Build Hyperamp as an electron/node based music library.  
- Build Hypertorrent: an electron based torrent client that bundles together hyperdrive and bittorrent/webtorrent into a unified client.  

Hyperamp will lay the groundwork for a music library app, let us mess around with music metadata and file indexing, familiarize us with choo better, and get us set up to build and distribute a desktop application.

Hypertorrent will be a nice complementary project to things like the dat and webtorrent desktop.  I imagine this as a traditional utorrent/[transmission](https://www.transmissionbt.com/) style torrent client.  In addition to handing torrents via [webtorrent](https://github.com/feross/webtorrent) as a way to get the application off the ground and back up a user interface, this should also allow for a traditional torrent client style experience with hyperdrive.  The important thing here is that we establish how to work with hyperdrive effectively, and experiment with some of its advanced features like signed feeds, self signed feeds, extracting unsigned feeds from signed feeds, feed updates, and feed history. 

Once we get these done, we should be pretty well set to start combining the two, and experimenting with synced libraries via hyperdrive.

What do you think @ungoldman ?

**Comment by ungoldman** [comment]
I think trying to finish a functional music player is a good first goal. That said I also think there's room for it to grow after that milestone has been reached. A music player that streams and across devices is more interesting than a winamp or itunes clone rewritten in node/electron.

I'm not sure what the importance of hyperdrive is in hypertorrent but I'm interested to see what you're thinking of doing with it.

If you want to try to do both projects separately at the same time it makes sense to create a second project, but since the first isn't close to functional yet I suggest we keep our ambitions humble and try to muddle through the basic music player portion of this project for now.

**Comment by bcomnes** [comment]
Ok lets roll with this
